get_latest_tweets:
  every: ["30s"]
  class: GetLatestTweets
  description: "resuqes!"

get_latest_gits:
  every: ["30s"]
  class: GetLatestGits
  description: "resuqes!"

get_latest_grams:
  every: ["30s"]
  class: GetLatestGrams
  description: "resuqes!"